title: ".codeVault {   }"
email: "contact [at] flowinho [com]"
author: "Florian Schuttkowski"
description: >- # this means to ignore newlines until "baseurl:"
  Durch meine Arbeit an verschiedensten Projekten lerne ich das Eine oder Andere. In meiner Freizeit werfe ich diese Elemente hier rein, zur späteren Referenzierung und zu eurer Unterhaltung.
dedication: >-
  Gewidmet meinen wundervollen Kindern. ♥️
permalink: :year/:month/:day/:title:output_ext
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: flowinho
github_username:  flowinho

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
